### PR TITLE
Add support for uuidgen

### PR DESCRIPTION
**Pull request by jc00ke**

### CODE REVIEW

**Comment by jc00ke** [comment]
Very cool plugin!

I couldn't get it working with `python` support in `neovim` but I do have `uuidgen` on my system.

I'm pretty new at `vimscript` so if it still doesn't work with the `Python` bindings let me know and I'll attempt to fix it. Seems like a relatively simple change though.

**Comment by jc00ke** [comment]
Hmm, `NuuidReplaceAll` doesn't seem to work, but I'm not sure if that's a `neovim` thing or what.

**Review by kburdett — APPROVED** [review]

**Comment by kburdett** [comment]
Thanks for the PR @jc00ke! Clearly I wasn't paying attention to my alerts :) I considered using uuidgen on the first pass, but thought Python would be more portable. Doesn't hurt to try both!

**Comment by jc00ke** [comment]
Ha, no worries... glad it works and thanks for the plugin in the first place!

**Pull request merged**
